#SPDX-License-Identifier: MIT-0
---
# tasks file for roles/nginx
- name: Install Nginx
  ansible.builtin.apt:
    name: "{{ nginx_package }}"
    state: present
    update_cache: true

- name: Deploy Nginx configuration
  ansible.builtin.template:
    src: default.conf.j2
    dest: /etc/nginx/sites-available/abc-order-service
    owner: root
    group: root
    mode: "0644"
  notify:
    - Reload Nginx

- name: Enable ABC Order Service site
  ansible.builtin.file:
    src: /etc/nginx/sites-available/abc-order-service
    dest: /etc/nginx/sites-enabled/abc-order-service
    state: link
  notify:
    - Reload Nginx

- name: Validate Nginx configuration
  ansible.builtin.command:
    cmd: nginx -t
  changed_when: false

