[app_servers]
app01 ansible_host=15.135.92.246
app02 ansible_host=15.134.204.195

[dev:children]
app_servers

[app_servers:vars]
ansible_user=ubuntu
ansible_ssh_private_key_file=~/.ssh/ansible-key.pem
